#!/bin/sh
RUN="/mnt/upgrade"
SWAP="/mnt/kernel/swap.img"

export HOME=/mnt
export SDL_NOMOUSE=1

if [ -e $SWAP ]
then
  swapon $SWAP
fi

modprobe r61520fb.ko

test -e $RUN
[ -e $RUN ]
rm -rf $RUN

/mnt/kernel/daemon
while [ 1 ]
do
  cd /mnt/gmenu2x; ./gmenu2x
done
